micronaut:
  application:
    name: hero
  security:
    basic-auth:
      enabled: true
    intercept-url-map:
      - pattern: /**/swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /**/swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins: ${ALLOWED_ORIGIN:``}
          allowedMethods:
            - OPTIONS
            - GET
            - POST
            - PUT
            - DELETE
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/hero_votes`}
    username: ${DATABASE_USER:`hero`}
    password: ${DATABASE_PASSWORD:`hero`}
#r2dbc:
#  datasources:
#    default:
#      url: r2dbc:postgresql://localhost:5432/hero_votes
#      username: hero
#      password: hero
jpa:
  default:
    entity-scan:
      packages:
        - 'dc.vilnius.hero.domain'
        - 'dc.vilnius.vote.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true
supabase:
  url: ${SUPABASE_URL}
  api-key: ${SUPABASE_API_KEY}
  token-endpoint: ${SUPABASE_TOKEN_URL:`/auth/v1/token?grant_type=password`}
