micronaut:
  application:
    name: hero
datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/hero_votes`}
    username: ${DATABASE_USER:`hero`}
    password: ${DATABASE_PASSWORD:`hero`}
#r2dbc:
#  datasources:
#    default:
#      url: r2dbc:postgresql://localhost:5432/hero_votes
#      username: hero
#      password: hero
jpa:
  default:
    entity-scan:
      packages:
        - 'dc.vilnius.hero.domain'
        - 'dc.vilnius.vote.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true
